version: "3.9"

services:
  deno_devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: deno
    container_name: deno_devcontainer
    volumes:
      - type: bind
        source: ..
        target: /workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
